name: sofra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf

    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-VariableFont_wght.ttf

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf

flutter_native_splash:
  color: "#A11518"
  image: assets/images/splash.png

  android_12:
    color: "#A11518"
    image: assets/images/splash.png
    icon_background_color: "#A11518"

  ios: true